#### Load the dataset

In [1]:
from sklearn.datasets import fetch_kddcup99
import pandas as pd

kdd = fetch_kddcup99(percent10 = True)

df = pd.DataFrame(
    kdd.data,
    columns = kdd.feature_names
)

df['target'] = kdd.target

df.sample(7)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,target
188398,0,b'icmp',b'ecr_i',b'SF',1032,0,0,0,0,0,...,255,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,b'smurf.'
240814,0,b'icmp',b'ecr_i',b'SF',1032,0,0,0,0,0,...,255,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,b'smurf.'
353888,0,b'tcp',b'private',b'S0',0,0,0,0,0,0,...,18,0.07,0.07,0.0,0.0,1.0,1.0,0.0,0.0,b'neptune.'
411835,0,b'icmp',b'ecr_i',b'SF',520,0,0,0,0,0,...,255,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,b'smurf.'
312442,0,b'icmp',b'ecr_i',b'SF',1032,0,0,0,0,0,...,255,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,b'smurf.'
288266,0,b'icmp',b'ecr_i',b'SF',1032,0,0,0,0,0,...,255,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,b'smurf.'
40104,0,b'tcp',b'http',b'SF',54540,8314,0,0,0,2,...,255,1.0,0.0,0.0,0.0,0.0,0.0,0.06,0.06,b'back.'

In [2]:
df['target'].value_counts()

target
b'smurf.'              280790
b'neptune.'            107201
b'normal.'              97278
b'back.'                 2203
b'satan.'                1589
b'ipsweep.'              1247
b'portsweep.'            1040
b'warezclient.'          1020
b'teardrop.'              979
b'pod.'                   264
b'nmap.'                  231
b'guess_passwd.'           53
b'buffer_overflow.'        30
b'land.'                   21
b'warezmaster.'            20
b'imap.'                   12
b'rootkit.'                10
b'loadmodule.'              9
b'ftp_write.'               8
b'multihop.'                7
b'phf.'                     4
b'perl.'                    3
b'spy.'                     2
Name: count, dtype: int64

In [3]:
df.shape

(494021, 42)

#### Preprocessing

In [4]:
print("Missing values : \n")
df.isnull().sum()

Missing values :

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
target                         0
dtype: int64

In [5]:
dup = df.duplicated().sum()
print(f"Duplicate values :\n{dup}")

Duplicate values :
348435

In [6]:
df.drop_duplicates(inplace = True)
print("Shape of the dataset after removing duplicates : ", df.shape)

Shape of the dataset after removing duplicates :  (145586, 42)

Converting bytes to string

In [7]:
for col in df.select_dtypes(include = ['object', 'string']).columns:
    try:
        df[col] = df[col].str.decode('utf-8')
    except:
        pass

Standardizing the text

In [8]:
for col in df.select_dtypes(include = ['object', 'string']).columns:
    df[col] = df[col].astype(str).str.lower().str.strip()

Label formatting

In [9]:
df['target'] = df['target'].astype(str).str.replace('.', '', regex = False)

Reducing noise in `service` column

In [10]:
count_service = df['service'].value_counts()
print(count_service)
rare = count_service[count_service < 200].index
df['service'] = df['service'].replace(rare, 'others')

service
http        62054
private     49057
smtp         9721
domain_u     5425
other        4769
            ...
x11            11
tim_i           5
pm_dump         1
tftp_u          1
red_i           1
Name: count, Length: 66, dtype: int64

Dropping constant columns

In [11]:
const = [c for c in df.columns if df[c].nunique() == 1]

df.drop(const, axis = 1, inplace = True)
print("Removed columns that are constant are :", const, "\n")
print(df.shape)

Removed columns that are constant are : ['num_outbound_cmds', 'is_host_login']

(145586, 40)

In [12]:
df['binary_target'] = df['target'].apply(lambda x: 0 if x == 'normal' else 1)
df['binary_target'].value_counts()

binary_target
0    87832
1    57754
Name: count, dtype: int64

In [13]:
X = df.drop(['target', 'binary_target'], axis = 1)
y = df['binary_target']

In [14]:
X = pd.get_dummies(X, columns = ['protocol_type', 'service', 'flag'])

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 45
)

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (116468, 66)
X_test shape: (29118, 66)

In [18]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 0.95)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#### ISOLATION FOREST

In [19]:
X_train = X_train[y_train == 0]

In [54]:
from sklearn.ensemble import IsolationForest

IF_model = IsolationForest(contamination = 0.2, random_state = 45)
IF_model.fit(X_train)

IsolationForest(contamination=0.2, random_state=45)

In [55]:
IF_y_pred = IF_model.predict(X_test)

IF_y_pred = [0 if pred == 1 else 1 for pred in IF_y_pred]
print(IF_y_pred[:100])

[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]

In [56]:
from sklearn.metrics import classification_report, accuracy_score

IF_acc = accuracy_score(y_test, IF_y_pred)
print("Accuracy is :", IF_acc)

IF_report = classification_report(y_test, IF_y_pred)
print(IF_report)

Accuracy is : 0.6118895528539048
              precision    recall  f1-score   support

           0       0.64      0.80      0.71     17495
           1       0.52      0.33      0.40     11623

    accuracy                           0.61     29118
   macro avg       0.58      0.56      0.56     29118
weighted avg       0.59      0.61      0.59     29118

#### One Class SVM

In [23]:
from sklearn.svm import OneClassSVM

SVM_model = OneClassSVM(
    kernel = 'rbf',
    gamma = 'scale',
    nu = 0.05
)

SVM_model.fit(X_train)

OneClassSVM(nu=0.05)

In [24]:
SVM_y_pred = SVM_model.predict(X_test)
SVM_y_pred = [0 if pred == 1 else 1 for pred in SVM_y_pred]

acc = accuracy_score(y_test, SVM_y_pred)
print("Accuracy is :", acc)

report = classification_report(y_test, SVM_y_pred)
print(report)

Accuracy is : 0.9607802733704238
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     17495
           1       0.93      0.98      0.95     11623

    accuracy                           0.96     29118
   macro avg       0.96      0.96      0.96     29118
weighted avg       0.96      0.96      0.96     29118

#### AutoEncoder

In [25]:
from sklearn.neural_network import MLPRegressor

autoencoder = MLPRegressor(
    hidden_layer_sizes = (32,16,32),
    activation = 'relu',
    solver = 'adam',
    max_iter = 100,
    random_state = 45
)

autoencoder.fit(X_train, X_train)

MLPRegressor(hidden_layer_sizes=(32, 16, 32), max_iter=100, random_state=45)

In [26]:
import numpy as np

X_reconstruct = autoencoder.predict(X_test)

error = np.mean(np.power(X_test - X_reconstruct, 2), axis = 1)

threshold = np.percentile(error, 60)
print(threshold)

0.046444552853542584

In [27]:
AE_pred = autoencoder.predict(X_test)
AE_pred = [1 if e > threshold else 0 for e in error]
print(AE_pred[:100])

[0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0]

In [28]:
from sklearn.metrics import accuracy_score, classification_report

acc = accuracy_score(y_test, AE_pred)
print(acc)

report = classification_report(y_test, AE_pred)
print(report)

0.9769901778968336
              precision    recall  f1-score   support

           0       0.98      0.98      0.98     17495
           1       0.97      0.97      0.97     11623

    accuracy                           0.98     29118
   macro avg       0.98      0.98      0.98     29118
weighted avg       0.98      0.98      0.98     29118

### TESTING

In [57]:
import joblib

joblib.dump(rare, 'rare_services.pkl')
joblib.dump(const, 'constant_columns.pkl')
joblib.dump(list(X.columns), 'feature_columns.pkl')

joblib.dump(scaler, 'scaler.pkl')
joblib.dump(pca, 'pca.pkl')
joblib.dump(threshold, 'threshold.pkl')

joblib.dump(IF_model, 'IF_model.pkl')
joblib.dump(autoencoder, 'autoencoder.pkl')
joblib.dump(SVM_model, 'SVM_model.pkl')

['SVM_model.pkl']

In [58]:
rare = joblib.load('rare_services.pkl')
const = joblib.load('constant_columns.pkl')
columns = joblib.load('feature_columns.pkl')

scaler = joblib.load('scaler.pkl')
pca = joblib.load('pca.pkl')
threshold = joblib.load('threshold.pkl')

IF_model = joblib.load('IF_model.pkl')
autoencoder = joblib.load('autoencoder.pkl')
SVM_model = joblib.load('SVM_model.pkl')

In [59]:
def preprocessing(data):
    
    df = data.copy()

    for col in df.select_dtypes(include = ['object', 'string']).columns:
        df[col] = df[col].astype(str).str.lower().str.strip()

    df['service'] = df['service'].apply(lambda x: 'others' if x in rare else x)

    df.drop(columns = [c for c in const if c in df.columns], inplace = True)

    df = pd.get_dummies(df, columns = ['protocol_type', 'service', 'flag'])

    for c in columns:
        if c not in df.columns:
            df[c] = 0
    df = df[columns]

    df = scaler.transform(df)
    df = pca.transform(df)

    return df

In [60]:
import numpy as np
import pandas as pd

In [65]:
def predict(data):

    trained = preprocessing(data)

    isolation_pred = IF_model.predict(trained)
    isolation_pred = ['Normal' if pred == 1 else 'Anomaly' for pred in isolation_pred]

    svm_pred = SVM_model.predict(trained)
    svm_pred = ['Normal' if pred == 1 else 'Anomaly' for pred in svm_pred]

    reconstruct = autoencoder.predict(trained)
    err = np.mean((trained - reconstruct) ** 2, axis = 1)
    autoencoder_pred = ['Normal' if e < threshold else 'Anomaly' for e in err]

    predictions = pd.DataFrame({
        'ISOLATION FOREST' : isolation_pred,
        'ONE CLASS SVM' : svm_pred,
        'AUTOENCODER' : autoencoder_pred
    })

    return predictions

In [66]:
test_data = df.sample(7, random_state = 45)
test_data = test_data.drop(columns = ['target', 'binary_target'])

op = predict(test_data)
op

  ISOLATION FOREST ONE CLASS SVM AUTOENCODER
0           Normal        Normal      Normal
1           Normal        Normal      Normal
2          Anomaly       Anomaly     Anomaly
3           Normal       Anomaly     Anomaly
4          Anomaly       Anomaly     Anomaly
5           Normal        Normal      Normal
6           Normal        Normal      Normal